export const CLEAR_SUCCESS = 'CLEAR_SUCCESS'

export const REGISTER_USER = 'REGISTER_UESR'
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS'
export const REGISTER_USER_FAILED = 'REGISTER_USER_FAILED'

export const SIGN_IN = 'SIGN_IN'
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS'
export const SIGN_IN_FAILED = 'SIGN_IN_FAILED'

export const SIGN_IN_CONFIRM_SIGNUP = 'SIGN_IN_CONFIRM_SIGNUP'

export const CONFIRM_SIGN_UP = 'CONFIRM_SIGN_UP'
export const SIGN_UP_CONFIRMED = 'SIGN_UP_CONFIRMED'
export const SIGN_UP_CONFIRMED_FAILED = 'SIGN_UP_CONFIRMED_FAILED'

export const GET_USERNAME = 'GET_USERNAME'

export const RESEND_VERIFICATION_CODE = 'RESEND_VERIFICATION_CODE'
export const RESEND_VERIFICATION_CODE_SUCCESS =
	'RESEND_VERIFICATION_CODE_SUCCESS'
export const RESEND_VERIFICATION_CODE_FAILED = 'RESEND_VERIFICATION_CODE_FAILED'

export const SET_USER = 'SET_USER'

export const SIGN_OUT = 'SIGN_OUT'

export const FORGOT_PASSWORD = 'FORGOT_PASSWORD'
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS'
export const FORGOT_PASSWORD_FAILED = 'FORGOT_PASSWORD_FAILED'
export const FORGOT_PASSWORD_RESET = 'FORGOT_PASSWORD_RESET'
export const FORGOT_PASSWORD_RESET_SUCCESS = 'FORGOT_PASSWORD_RESET_SUCCESS'
export const FORGOT_PASSWORD_RESET_FAILED = 'FORGOT_PASSWORD_RESET_FAILED'
export const VERIFY_OTP = 'VERIFY_OTP'
export const VERIFY_OTP_SUCCESS = 'VERIFY_OTP_SUCCESS'
export const VERIFY_OTP_FAILED = 'VERIFY_OTP_FAILED'
export const RESEND_OTP = 'RESEND_OTP'

export const CHANGE_PASSWORD = 'CHANGE_PASSWORD'
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS'
export const CHANGE_PASSWORD_FAILED = 'CHANGE_PASSWORD_FAILED'

export const COMPLETE_PASSWORD = 'COMPLETE_PASSWORD'
export const COMPLETE_NEW_PASSWORD_REQUEST = 'COMPLETE_NEW_PASSWORD_REQUEST'
export const COMPLETE_NEW_PASSWORD_SUCCESS = 'COMPLETE_NEW_PASSWORD_SUCCESS'
export const COMPLETE_NEW_PASSWORD_FAILED = 'COMPLETE_NEW_PASSWORD_FAILED'

export const CREATE_USER = 'CREATE_USER'
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS'
export const CREATE_USER_FAILED = 'CREATE_USER_FAILED'
