const devEnv = {
	REGION: process.env.REACT_APP_REGION,
	COGNITO_USER_POOL_ID: process.env.REACT_APP_COGNITO_USER_POOL_ID,
	COGNITO_USER_POOL_WEB_CLIENT_ID:
		process.env.REACT_APP_COGNITO_USER_POOL_WEB_CLIENT_ID,
	COGNITO_GATEWAY: process.env.REACT_APP_COGNITO_GATEWAY,
	BACKEND_API_GATEWAY: process.env.REACT_APP_BACKEND_API_GATEWAY,
}

export default devEnv
